version: "3"

services:
  jupyter:
    image: nbgallery/base-notebook
    ports:
      - "8888:8888"
    environment:
      NBGALLERY_URL: http://localhost:3000
      NBGALLERY_ENABLE_INSTRUMENTATION: 1
      NBGALLERY_ENABLE_AUTODOWNLOAD: 1
